# Batería
BATERIA_MAX_COCINERO = 100
BATERIA_MAX_CAMARERO = 120
COSTO_BATERIA_ENTREGA = 10
COSTO_BATERIA_RAPIDA = 15
COSTO_BATERIA_GOURMET = 25

# Tiempos
TIEMPO_SIMULACION_REINTENTO = 5
TIEMPO_SIMULACION_FINAL = 3
TIEMPO_PREPARACION_GOURMET = 0.1

# Stock Inicial
STOCK_INICIAL_DEFAULT = 1000